name: Publish Docker

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: "sensirion/embedded-ci"
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . -t "$DOCKER_REPO":${GITHUB_REF##*/}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push all tags
        run: docker push "$DOCKER_REPO":${GITHUB_REF##*/}